#!/bin/sh
#SBATCH -N 2
#SBATCH -p RM-shared
#SBATCH -t 5:00:00
#SBATCH --ntasks-per-node=128

INPUT=""
TEMP=""
OUTPUT=""

_usage="
Usage: $0 [OPTIONS]
Options:
  [ -i INPUT_DIR ],          Required. Absolute path to input files directory.
  [ -o OUTPUT_DIR ],         Optional. Absolute path to output files directory. Defualt as INPUT_DIR.
  [ -t TEMP_DIR ],           Optional. Absolute path to temporary files directory. Defualt as INPUT_DIR.
  [ -h ],                    Help manuals.
"

usage() {                                 # Function: Print a help message.
  echo "$_usage" 1>&2 
}

exit_abnormal() {                         # Function: Exit with error.
  usage
  exit 1
}

while getopts ":i:o:t:h" options; do         # use silent error checking;
                                          
  case "${options}" in                    
    i)                                    # If the option is i,
      INPUT=${OPTARG}                     # set $INPUT to specified value.
      ;;
    o)                                    # If the option is o,
      OUTPUT=${OPTARG}                    # set $OUTPUT to specified value.
      ;;
    t)                                    # If the option is t,
      TEMP=${OPTARG}                      # set $TEMP to specified value.
      ;;
    h)                                    # If the option is h,
      usage
      exit 0                      		    # print help manuals.
      ;;
    :)                                    # If expected argument omitted:
      echo "Error: -${OPTARG} requires an argument."
      exit_abnormal                       # Exit abnormally.
      ;;
    *)									  # If unknown (any other) option:
      echo "Error: Unknow option provided."                                    
      exit_abnormal                       # Exit abnormally.
      ;;
  esac
done


if [ "$INPUT" = "" ]; then                 # If $INPUT is an empty string,
  echo "Error: must provide INPUT_DIR."
  exit_abnormal                       
fi

if [ "$TEMP" = "" ]; then                  # If $TEMP is an empty string,
  TEMP=$INPUT                        
fi

if [ "$OUTPUT" = "" ]; then                # If $OUTPUT is an empty string,
  OUTPUT=$INPUT                       
fi

################
################
#Pipeline starts
################
################
TRIMMED_1_1="${TEMP}/rep1.r1.fqTr.fq"
TRIMMED_1_2="${TEMP}/rep1.r2.fqTr.fq"
#############
#Trim adapter
#############
##Rep1
#Round 1
cutadapt \
-f fastq \
--match-read-wildcards \
--times 1 \
-e 0.1 \
-O 1 \
--quality-cutoff 6 \
-m 18 \
-a NNNNNAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC \
-g CTTCCGATCTACAAGTT \
-g CTTCCGATCTTGGTCCT \
-A AACTTGTAGATCGGA \
-A AGGACCAAGATCGGA \
-A ACTTGTAGATCGGAA \
-A GGACCAAGATCGGAA \
-A CTTGTAGATCGGAAG \
-A GACCAAGATCGGAAG \
-A TTGTAGATCGGAAGA \
-A ACCAAGATCGGAAGA \
-A TGTAGATCGGAAGAG \
-A CCAAGATCGGAAGAG \
-A GTAGATCGGAAGAGC \
-A CAAGATCGGAAGAGC \
-A TAGATCGGAAGAGCG \
-A AAGATCGGAAGAGCG \
-A AGATCGGAAGAGCGT \
-A GATCGGAAGAGCGTC \
-A ATCGGAAGAGCGTCG \
-A TCGGAAGAGCGTCGT \
-A CGGAAGAGCGTCGTG \
-A GGAAGAGCGTCGTGT \
-o "$TRIMMED_1_1" \
-p "$TRIMMED_1_2" \
rep1.r1.fq \
rep1.r2.fq


exit 0                                     # Exit normally.